workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: codemanagekeychillAdmin
    environment:
      vars:
        APP_STORE_APPLE_ID: 6473549599
        BUNDLE_ID: "com.chillnow.ios.client"
        XCODE_SCHEME: "ChillnowApp"
        DEVELOPMENT_TEAM: "BUAXN7XNMZ"
        node: 18.18.2
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.chillnow.ios.client
    scripts:
      - name: Install dependencies
        script: |
          npm cache clean --force
          rm -rf node_modules
          npm install
          npm install -g expo-cli@latest
          npm install -g eas-cli@latest
          
      - name: Update Expo dependencies
        script: |
          npx expo install @react-native-async-storage/async-storage@1.21.0
          npx expo install @react-native-picker/picker@2.6.1
          npx expo install react-native@0.73.6
          npx expo install react-native-maps@1.10.0
          npx expo install react-native-safe-area-context@4.8.2
          npx expo install --fix
          
      - name: Run Expo Prebuild
        script: |
          rm -rf ios android
          npx expo prebuild --platform ios --clean

      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/ios/$XCODE_SCHEME/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST || true

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Create exportOptions.plist
        script: |
          mkdir -p ios/build
          cat > ios/exportOptions.plist << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$DEVELOPMENT_TEAM</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
              <key>provisioningProfiles</key>
              <dict>
                  <key>com.chillnow.ios.client</key>
                  <string>match AppStore $BUNDLE_ID</string>
              </dict>
          </dict>
          </plist>
          EOL

      - name: Increment build number
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          cd ios
          xcrun agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
          cd ..

      - name: Build ipa for App Store
        script: |
          cd ios
          # Clean build folder
          rm -rf build
          mkdir -p build
          
          # Set build settings
          ARCHIVE_PATH="$PWD/build/ChillnowApp.xcarchive"
          EXPORT_PATH="$PWD/build/ipa"
          
          # Build archive
          xcodebuild clean archive \
            -workspace "ChillnowApp.xcworkspace" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -allowProvisioningUpdates \
            -destination 'generic/platform=iOS' \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PROVISIONING_PROFILE_SPECIFIER="match AppStore $BUNDLE_ID" \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            CODE_SIGN_STYLE="Manual" \
            SWIFT_OPTIMIZATION_LEVEL="-O" \
            SWIFT_COMPILATION_MODE=wholemodule \
            OTHER_SWIFT_FLAGS="-D RELEASE"

          # Export archive
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist "exportOptions.plist" \
            -exportPath "$EXPORT_PATH" \
            -allowProvisioningUpdates

    artifacts:
      - ios/build/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - chillnow225@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Testers
        submit_to_app_store: true
        cancel_previous_submissions: true
        release_type: SCHEDULED
        earliest_release_date: 2025-03-01T14:00:00+00:00
        phased_release: true
