workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemanagekeychillAdmin
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.chillnow.ios.client
      vars:
        BUNDLE_ID: "com.chillnow.ios.client"
        XCODE_WORKSPACE: "CodemagicSample.xcworkspace"
        XCODE_SCHEME: "CodemagicSample"
        APP_STORE_APPLE_ID: 6473549599
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install
      - name: Increment build number
        script: |
          cd ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for App Store
        script: |
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Testers
