workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: codemanagekeychillAdmin
    environment:
      vars:
        APP_STORE_APPLE_ID: 6473549599
        BUNDLE_ID: "com.chillnow.ios.client"
        XCODE_SCHEME: "ChillnowApp"
        DEVELOPMENT_TEAM: "BUAXN7XNMZ"
        node: 18.18.2
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.chillnow.ios.client
    scripts:
      - name: Install dependencies
        script: |
          npm cache clean --force
          rm -rf node_modules
          npm install
          npm install -g expo-cli@latest
          npm install -g eas-cli@latest
          
      - name: Update Expo dependencies
        script: |
          npx expo install @react-native-async-storage/async-storage@1.21.0
          npx expo install @react-native-picker/picker@2.6.1
          npx expo install react-native@0.73.6
          npx expo install react-native-maps@1.10.0
          npx expo install react-native-safe-area-context@4.8.2
          npx expo install --fix
          
      - name: Run Expo Prebuild
        script: |
          rm -rf ios android
          npx expo prebuild --platform ios --clean

      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/ios/$XCODE_SCHEME/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST || true

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod deintegrate
          pod cache clean --all
          pod install
          cd ..

      - name: Create exportOptions.plist
        script: |
          mkdir -p ios/build
          cat > ios/exportOptions.plist << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$DEVELOPMENT_TEAM</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOL

      - name: Set up code signing settings
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Increment build number
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          cd ios
          xcrun agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
          cd ..

      - name: Build ipa for App Store
        script: |
          cd ios
          
          # Clean and create build directory
          rm -rf build
          mkdir -p build
          
          # Set environment variables
          export DEVELOPER_DIR="/Applications/Xcode.app/Contents/Developer"
          export PATH="$DEVELOPER_DIR/usr/bin:$PATH"
          
          # Build archive
          xcodebuild \
            -workspace ChillnowApp.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath build/ChillnowApp.xcarchive \
            clean archive \
            CODE_SIGN_IDENTITY="iPhone Distribution" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE="Automatic" \
            ENABLE_BITCODE=NO \
            | xcpretty && exit ${PIPESTATUS[0]}
          
          # Export IPA
          xcodebuild -exportArchive \
            -archivePath build/ChillnowApp.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/ipa \
            -allowProvisioningUpdates \
            | xcpretty && exit ${PIPESTATUS[0]}

    artifacts:
      - ios/build/ipa/*.ipa
      - ios/build/ChillnowApp.xcarchive/dSYMs/*

    publishing:
      email:
        recipients:
          - chillnow225@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Testers
        submit_to_app_store: true
        cancel_previous_submissions: true
        release_type: SCHEDULED
        earliest_release_date: 2025-03-01T14:00:00+00:00
        phased_release: true
