workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: codemanagekeychillAdmin  # Remplace par le nom exact de ton intégration Codemagic
    environment:
      vars:
        APP_STORE_APPLE_ID: 6473549599
        BUNDLE_ID: "com.chillnow.ios.client"
        XCODE_SCHEME: "ChillnowApp"  # Remplace par ton scheme exact
        node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm install -g expo-cli
          
      - name: Run Expo Prebuild
        script: |
          npx expo prebuild --clean

      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/ios/$XCODE_SCHEME/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST

      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install

      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))

      - name: Build ipa for App Store
        script: |
          xcodebuild -project "$CM_BUILD_DIR/ios/ChillnowApp.xcodeproj" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/ios/build/ChillnowApp.xcarchive" archive

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/ios/build/ChillnowApp.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ios/exportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/build/ios/ipa"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - chillnow225@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Testers
        submit_to_app_store: true
        cancel_previous_submissions: true
        release_type: SCHEDULED
        earliest_release_date: 2025-03-01T14:00:00+00:00
        phased_release: true
