workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: codemanagekeychillAdmin
    environment:
      vars:
        APP_STORE_APPLE_ID: 6473549599
        BUNDLE_ID: "com.chillnow.ios.client"
        XCODE_SCHEME: "ChillnowApp"
        node: 18.18.2
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm cache clean --force
          rm -rf node_modules
          npm install
          npm install -g expo-cli@latest
          npm install -g eas-cli@latest
          
      - name: Update Expo dependencies
        script: |
          npx expo install @react-native-async-storage/async-storage@1.21.0
          npx expo install @react-native-picker/picker@2.6.1
          npx expo install react-native@0.73.6
          npx expo install react-native-maps@1.10.0
          npx expo install react-native-safe-area-context@4.8.2
          npx expo install --fix
          
      - name: Run Expo Prebuild
        script: |
          rm -rf ios android
          npx expo prebuild --platform ios --clean

      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/ios/$XCODE_SCHEME/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST

      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install && cd ..

      - name: Increment build number
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          cd ios
          xcrun agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
          cd ..

      - name: Build ipa for App Store
        script: |
          cd ios
          xcodebuild -project "ChillnowApp.xcodeproj" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "build/ChillnowApp.xcarchive" archive

          xcodebuild -exportArchive \
            -archivePath "build/ChillnowApp.xcarchive" \
            -exportOptionsPlist "exportOptions.plist" \
            -exportPath "build/ipa"

    artifacts:
      - ios/build/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - chillnow225@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Testers
        submit_to_app_store: true
        cancel_previous_submissions: true
        release_type: SCHEDULED
        earliest_release_date: 2025-03-01T14:00:00+00:00
        phased_release: true
