workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemanagekeychillAdmin  # Remplace par le nom exact de ton intégration Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.chillnow.ios.client
      vars:
        BUNDLE_ID: "com.chillnow.ios.client"
        XCODE_SCHEME: "ChillnowApp"  # Remplace par le bon scheme de ton app
        APP_STORE_APPLE_ID: 6473549599
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios && pod install

      - name: Run Expo Prebuild (si nécessaire)
        script: |
          if [ ! -d "ios" ]; then
            npx expo prebuild
          fi

      - name: Increment build number
        script: |
          cd ios
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))

      - name: Build ipa for App Store
        script: |
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/ios/ChillnowApp.xcodeproj"\  # Assure-toi que ce fichier existe
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - chillnow225@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Testers
